# The manifest for the "alertmanager" service.

# Descriptions
name: alertmanager
type: Backend Service

# Container settings
image:
  build: Dockerfile.alertmanager
  port: 9093

# Service in the cluster settings
cpu: 256     # 256 means 0.25 vCPU.
memory: 512  # Amount in MiB.
platform: linux/x86_64
count: 1     # Number of tasks that should be running in your service.
exec: true   # Enable running commands in your container.

# Secret settings
secrets:
  SLACK_WEBHOOK_URL: /copilot/monitoring/production/secrets/SLACK_WEBHOOK_URL
